name: Helium Auto Update

on:
  schedule:
    - cron: "0 8 * * *" # runs every day at 08:00 UTC
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  # 1. Update the Manifest File
  update-manifest:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run update script
        run: bash ./grab_latest.sh
        
      - name: Check and Commit
        id: check
        run: |
          git config --global user.name "helium-bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status -s net.imput.helium.yml) ]]; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
            VERSION=$(grep -m1 'version:' version.txt | awk '{print $2}')
            git add net.imput.helium.yml net.imput.helium.metainfo.xml version.txt
            git commit -m "update: helium $VERSION"
            git push origin HEAD:main
          else
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          fi
