on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'warning'
        type: choice
        options:
          - opencloud-desktop
          - flora-desktop

name: Flatpak build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
    - run: |
        if [ "${{ inputs.branch }}" = "opencloud-desktop" ]; then
          echo "FLATPAK_MANIFEST=eu.opencloud.desktop.opencloud.yml" >> $GITHUB_ENV
        elif [ "${{ inputs.branch }}" = "flora-desktop" ]; then
          echo "FLATPAK_MANIFEST=com.damillora.flora.yml" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        submodules: 'true'
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ${{ inputs.branch }}.flatpak
        manifest-path:  ${{ env.FLATPAK_MANIFEST }}
        cache-key: flatpak-builder-${{ inputs.branch }}-${{ github.sha }}
        arch: x86_64
    - uses: flatpak/flatpak-github-actions/flat-manager@v6
      name: "Deploy"
      with:
        repository: synchronists
        flat-manager-url: https://flatpak.aemeath.nanao.moe
        token: ${{ secrets.SYNCHRONISTS_TOKEN }}
